#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
setxkbmap br &
feh --bg-scale --randomize /usr/share/pixmaps/astronauts/ &
polybar my_bar &
dunst &
picom -b &
echo OFF > /tmp/POLYBAR_STATE.txt

bspc monitor -d 1 2 3 4 5

bspc config border_width            1
bspc config window_gap              5

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc config normal_border_color	"#44475a"
bspc config active_border_color	"#bd93f9"
bspc config focused_border_color	"#4DA6FF"
#bspc config focused_border_color	"#ff79c6"
bspc config presel_feedback_color   "#6272a4"

bspc config right_padding 0
bspc config bottom_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
